param([Parameter(Mandatory=$true)][string]$RepoRoot)
$ErrorActionPreference="Stop"
Set-StrictMode -Version Latest

function EnsureDir([string]$p){
  if([string]::IsNullOrWhiteSpace($p)){ throw "EnsureDir: empty path" }
  if(-not (Test-Path -LiteralPath $p -PathType Container)){
    New-Item -ItemType Directory -Force -Path $p | Out-Null
  }
}

function WriteUtf8NoBomLf([string]$Path,[string]$Text){
  if([string]::IsNullOrWhiteSpace($Path)){ throw "WriteUtf8NoBomLf: empty path" }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $t = $Text -replace "`r`n","`n"
  $t = $t -replace "`r","`n"
  if(-not $t.EndsWith("`n")){ $t += "`n" }
  EnsureDir (Split-Path -Parent $Path)
  [System.IO.File]::WriteAllText($Path,$t,$enc)
}

function WriteLines([string]$Path,[string[]]$Lines){
  $txt = ((@($Lines) -join "`n") + "`n")
  WriteUtf8NoBomLf $Path $txt
}

$panelPath = Join-Path $RepoRoot "app\src\acompute\ui\DemoShift2Panel.tsx"
EnsureDir (Split-Path -Parent $panelPath)

WriteLines $panelPath @(
'import React, { useMemo, useState } from "react";'
'import type { Bit } from "../core/types";'
'import { initialState } from "../core/state";'
'import { transition } from "../core/transition";'
'import { evalGraph } from "../engine/eval";'
'import { demoShift2 } from "../demos/demo_shift2";'
''
'type Outs = Record<string, Bit>;'
'type Mode = "engine" | "manual";'
''
'function bitLabel(b: Bit): string {'
'  return b === 1 ? "1" : "0";'
'}'
''
'function onlyBits(s: string): string {'
'  return (s || "").replace(/[^01]/g, "");'
'}'
''
'function SvgGraph(props: { outs: Outs }) {'
'  const { outs } = props;'
'  const g = demoShift2;'
'  const w = 560;'
'  const h = 240;'
'  return ('
'    <svg width={w} height={h} style={{ border: "1px solid #2a3a52", borderRadius: 14, background: "#070d16" }}>'
'      {g.edges.map((e) => {'
'        const a = g.nodes.find((n) => n.id === e.from);'
'        const b = g.nodes.find((n) => n.id === e.to);'
'        if (!a || !b) return null;'
'        const x1 = a.x + 52;'
'        const y1 = a.y;'
'        const x2 = b.x - 52;'
'        const y2 = b.y;'
'        const mx = (x1 + x2) / 2;'
'        const d = `M ${x1} ${y1} C ${mx} ${y1}, ${mx} ${y2}, ${x2} ${y2}`;'
'        return <path key={e.id} d={d} fill="none" stroke="#93b8ff" strokeWidth={2.5} opacity={0.9} />;'
'      })}'
''
'      {g.nodes.map((n) => {'
'        const out = (outs[n.id] ?? 0) as Bit;'
'        const rx = 54;'
'        const ry = 24;'
'        return ('
'          <g key={n.id}>'
'            <rect x={n.x - rx} y={n.y - ry} width={rx * 2} height={ry * 2} rx={12} ry={12} fill="#0b1422" stroke="#3b557a" />'
'            <text x={n.x} y={n.y - 4} textAnchor="middle" fontSize="13" fill="#ffffff" fontFamily="ui-sans-serif, system-ui">{n.label}</text>'
'            <text x={n.x} y={n.y + 16} textAnchor="middle" fontSize="14" fill="#00ff95" fontFamily="ui-monospace, SFMono-Regular, Menlo">{bitLabel(out as Bit)}</text>'
'          </g>'
'        );'
'      })}'
'    </svg>'
'  );'
'}'
''
'export function DemoShift2Panel() {'
'  const [d0, setD0] = useState<Bit>(0);'
'  const [s, setS] = useState(() => initialState());'
'  const [mode, setMode] = useState<Mode>("engine");'
'  const [seqText, setSeqText] = useState<string>("1010");'
'  const [seqIdx, setSeqIdx] = useState<number>(0);'
''
'  const outs = useMemo(() => {'
'    return evalGraph(s, demoShift2, { D0: d0 });'
'  }, [s, d0]);'
''
'  const q0 = (outs["Q0"] ?? 0) as Bit;'
'  const q1 = (outs["Q1"] ?? 0) as Bit;'
''
'  function manualShift(prev: any, bit: Bit): any {'
'    const prevSeq = (prev && prev.seq) ? prev.seq : {};'
'    const prevQ0 = ((prevSeq["Q0"] ?? 0) as Bit);'
'    const nextSeq: any = { ...prevSeq, Q0: bit, Q1: prevQ0 };'
'    return { ...prev, clk: 0, seq: nextSeq };'
'  }'
''
'  function pulseOnce(bit: Bit) {'
'    setS((prev) => {'
'      if (mode === "manual") {'
'        return manualShift(prev, bit);'
'      }'
'      const s1 = transition(prev, demoShift2, { D0: bit }, 1);'
'      const s2 = transition(s1, demoShift2, { D0: bit }, 0);'
'      return s2;'
'    });'
'  }'
''
'  function stepSequence() {'
'    const bits = onlyBits(seqText);'
'    if (bits.length === 0) return;'
'    const i = seqIdx % bits.length;'
'    const b = (bits.charAt(i) === "1" ? 1 : 0) as Bit;'
'    setD0(b);'
'    pulseOnce(b);'
'    setSeqIdx(i + 1);'
'  }'
''
'  function loadSequence() {'
'    const bits = onlyBits(seqText);'
'    setSeqText(bits);'
'    setSeqIdx(0);'
'    setS(() => initialState());'
'    if (bits.length > 0) {'
'      const b = (bits.charAt(0) === "1" ? 1 : 0) as Bit;'
'      setD0(b);'
'    }'
'  }'
''
'  return ('
'    <div style={{ padding: 16, color: "#ffffff", fontFamily: "ui-sans-serif, system-ui", background: "#05070c", minHeight: "100vh" }}>'
'      <h1 style={{ margin: 0, fontSize: 22 }}>ACompute - MVP3 Shift Register (2x DFF)</h1>'
'      <div style={{ marginTop: 8, opacity: 0.9 }}>'
'        D0 -> Q0, and Q0 -> D1 -> Q1. Pulse performs clk 0->1->0 (rising edge capture).'
'      </div>'
''
'      <div style={{ display: "flex", gap: 10, marginTop: 14, alignItems: "center", flexWrap: "wrap" }}>'
'        <button'
'          onClick={() => setD0(d0 === 1 ? 0 : 1)}'
'          style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}'
'        >'
'          Toggle D0 (now {bitLabel(d0)})'
'        </button>'
''
'        <button'
'          onClick={() => pulseOnce(d0)}'
'          style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#152540", color: "#ffffff" }}'
'        >'
'          Pulse (0->1->0)'
'        </button>'
''
'        <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.95 }}>'
'          Q0={bitLabel(q0)} Q1={bitLabel(q1)} clk={bitLabel((s as any).clk ?? 0)}'
'        </div>'
'      </div>'
''
'      <div style={{ display: "flex", gap: 10, marginTop: 12, alignItems: "center", flexWrap: "wrap" }}>'
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>'
'          <span style={{ opacity: 0.95 }}>Mode</span>'
'          <select'
'            value={mode}'
'            onChange={(e) => setMode(e.target.value as Mode)}'
'            style={{ padding: "6px 8px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}'
'          >'
'            <option value="engine">Engine (transition)</option>'
'            <option value="manual">Manual (guaranteed shift)</option>'
'          </select>'
'        </label>'
''
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>'
'          <span style={{ opacity: 0.95 }}>Input bits</span>'
'          <input'
'            value={seqText}'
'            onChange={(e) => setSeqText(onlyBits(e.target.value))}'
'            placeholder="e.g. 101001"'
'            style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff", width: 180 }}'
'          />'
'        </label>'
''
'        <button'
'          onClick={loadSequence}'
'          style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}'
'        >'
'          Load (reset)'
'        </button>'
''
'        <button'
'          onClick={stepSequence}'
'          style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#152540", color: "#ffffff" }}'
'        >'
'          Step next bit'
'        </button>'
''
'        <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.9 }}>'
'          seqIdx={seqIdx}'
'        </div>'
'      </div>'
''
'      <div style={{ marginTop: 14 }}><SvgGraph outs={outs} /></div>'
''
'      <div style={{ marginTop: 14, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>'
'        <div style={{ border: "1px solid #2a3a52", borderRadius: 12, padding: 12, background: "#070d16" }}>'
'          <div style={{ fontWeight: 700, marginBottom: 6 }}>Sequential state (s.seq)</div>'
'          <pre style={{ margin: 0, fontSize: 12, whiteSpace: "pre-wrap", color: "#ffffff" }}>{JSON.stringify((s as any).seq, null, 2)}</pre>'
'        </div>'
'        <div style={{ border: "1px solid #2a3a52", borderRadius: 12, padding: 12, background: "#070d16" }}>'
'          <div style={{ fontWeight: 700, marginBottom: 6 }}>Combinational outs</div>'
'          <pre style={{ margin: 0, fontSize: 12, whiteSpace: "pre-wrap", color: "#ffffff" }}>{JSON.stringify(outs, null, 2)}</pre>'
'        </div>'
'      </div>'
'    </div>'
'  );'
'}'
)

Write-Host ("PATCH_OK: wrote " + $panelPath) -ForegroundColor Green
Write-Host "NOTE: restart Vite dev server if needed (press r in the Vite terminal)" -ForegroundColor Yellow
