param([Parameter(Mandatory=$true)][string]$RepoRoot)
$ErrorActionPreference="Stop"
Set-StrictMode -Version Latest

function EnsureDir([string]$p){
  if([string]::IsNullOrWhiteSpace($p)){ throw "EnsureDir: empty path" }
  if(-not (Test-Path -LiteralPath $p -PathType Container)){
    New-Item -ItemType Directory -Force -Path $p | Out-Null
  }
}
function WriteUtf8NoBomLf([string]$Path,[string[]]$Lines){
  if([string]::IsNullOrWhiteSpace($Path)){ throw "WriteUtf8NoBomLf: empty path" }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $text = (@($Lines) -join "`n")
  $text = ($text -replace "`r`n","`n") -replace "`r","`n"
  if(-not $text.EndsWith("`n")){ $text += "`n" }
  EnsureDir (Split-Path -Parent $Path)
  [System.IO.File]::WriteAllText($Path,$text,$enc)
}

$panelPath = Join-Path $RepoRoot "app\src\acompute\ui\DemoShift2Panel.tsx"
if(-not (Test-Path -LiteralPath $panelPath -PathType Leaf)){ throw ("MISSING_PANEL: " + $panelPath) }

$tsx = New-Object System.Collections.Generic.List[string]
[void]$tsx.Add('import React, { useEffect, useMemo, useRef, useState } from "react";')
[void]$tsx.Add('import type { Bit } from "../core/types";')
[void]$tsx.Add('import { initialState } from "../core/state";')
[void]$tsx.Add('import { transition } from "../core/transition";')
[void]$tsx.Add('import { evalGraph } from "../engine/eval";')
[void]$tsx.Add('import { demoShift2 } from "../demos/demo_shift2";')
[void]$tsx.Add('')
[void]$tsx.Add('type Outs = Record<string, Bit>;')
[void]$tsx.Add('type Mode = "engine" | "manual";')
[void]$tsx.Add('type Phase = "low" | "rise" | "high" | "fall";')
[void]$tsx.Add('type Sample = { d0: Bit; q0: Bit; q1: Bit; clk: Bit };')
[void]$tsx.Add('type TraceEntry = {')
[void]$tsx.Add('  tick: number;')
[void]$tsx.Add('  phase: Phase;')
[void]$tsx.Add('  d0: Bit;')
[void]$tsx.Add('  q0: Bit;')
[void]$tsx.Add('  q1: Bit;')
[void]$tsx.Add('  clk: Bit;')
[void]$tsx.Add('  mode: Mode;')
[void]$tsx.Add('  seqIdx: number;')
[void]$tsx.Add('};')
[void]$tsx.Add('')
[void]$tsx.Add('function bitLabel(b: Bit): string {')
[void]$tsx.Add('  return b === 1 ? "1" : "0";')
[void]$tsx.Add('}')
[void]$tsx.Add('')
[void]$tsx.Add('function onlyBits(s: string): string {')
[void]$tsx.Add('  return (s || "").replace(/[^01]/g, "");')
[void]$tsx.Add('}')
[void]$tsx.Add('')
[void]$tsx.Add('function clamp(n: number, lo: number, hi: number): number {')
[void]$tsx.Add('  if (n < lo) return lo;')
[void]$tsx.Add('  if (n > hi) return hi;')
[void]$tsx.Add('  return n;')
[void]$tsx.Add('}')
[void]$tsx.Add('')
[void]$tsx.Add('function Waveform(props: { samples: Sample[]; playhead: number; phase: string }) {')
[void]$tsx.Add('  const { samples, playhead, phase } = props;')
[void]$tsx.Add('  const w = 860;')
[void]$tsx.Add('  const rowH = 34;')
[void]$tsx.Add('  const padL = 70;')
[void]$tsx.Add('  const padR = 16;')
[void]$tsx.Add('  const padT = 10;')
[void]$tsx.Add('  const n = Math.max(2, samples.length);')
[void]$tsx.Add('  const step = (w - padL - padR) / (n - 1);')
[void]$tsx.Add('')
[void]$tsx.Add('  function yBase(row: number): number {')
[void]$tsx.Add('    return padT + row * rowH + 18;')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  function mkPath(get: (s: Sample) => Bit, row: number): string {')
[void]$tsx.Add('    if (samples.length === 0) return "";')
[void]$tsx.Add('    const y0 = yBase(row);')
[void]$tsx.Add('    const hi = y0 - 12;')
[void]$tsx.Add('    const lo = y0 + 8;')
[void]$tsx.Add('    let d = "";')
[void]$tsx.Add('    let x = padL;')
[void]$tsx.Add('    let y = get(samples[0]) ? hi : lo;')
[void]$tsx.Add('    d += `M ${x} ${y}`;')
[void]$tsx.Add('    for (let i = 1; i < samples.length; i++) {')
[void]$tsx.Add('      const nx = padL + i * step;')
[void]$tsx.Add('      const ny = get(samples[i]) ? hi : lo;')
[void]$tsx.Add('      d += ` L ${nx} ${y}`;')
[void]$tsx.Add('      if (ny !== y) d += ` L ${nx} ${ny}`;')
[void]$tsx.Add('      x = nx;')
[void]$tsx.Add('      y = ny;')
[void]$tsx.Add('    }')
[void]$tsx.Add('    return d;')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  const h = padT + rowH * 4 + 10;')
[void]$tsx.Add('  const px = padL + clamp(playhead, 0, n - 1) * step;')
[void]$tsx.Add('')
[void]$tsx.Add('  return (')
[void]$tsx.Add('    <svg width={w} height={h} style={{ border: "1px solid #2a3a52", borderRadius: 12, background: "#070d16" }}>')
[void]$tsx.Add('      <text x={12} y={18} fontSize={12} fill="#ffffff" fontFamily="ui-monospace, SFMono-Regular, Menlo" opacity={0.9}>')
[void]$tsx.Add('        Waveform (last {samples.length} samples)')
[void]$tsx.Add('      </text>')
[void]$tsx.Add('      <line x1={px} y1={6} x2={px} y2={h - 6} stroke="#ffffff" strokeWidth={1} opacity={0.18} />')
[void]$tsx.Add('      <rect x={w - 210} y={6} width={196} height={22} rx={10} ry={10} fill="#0b1422" stroke="#2a3a52" />')
[void]$tsx.Add('      <text x={w - 200} y={22} fontSize={12} fill="#ffffff" fontFamily="ui-monospace, SFMono-Regular, Menlo" opacity={0.9}>')
[void]$tsx.Add('        phase={phase} idx={playhead}')
[void]$tsx.Add('      </text>')
[void]$tsx.Add('')
[void]$tsx.Add('      {["D0", "Q0", "Q1", "clk"].map((lab, i) => (')
[void]$tsx.Add('        <g key={lab}>')
[void]$tsx.Add('          <text x={12} y={yBase(i)} fontSize={12} fill="#ffffff" fontFamily="ui-monospace, SFMono-Regular, Menlo" opacity={0.9}>')
[void]$tsx.Add('            {lab}')
[void]$tsx.Add('          </text>')
[void]$tsx.Add('          <line x1={padL} y1={yBase(i) + 8} x2={w - padR} y2={yBase(i) + 8} stroke="#1c2a3b" strokeWidth={1} />')
[void]$tsx.Add('          <line x1={padL} y1={yBase(i) - 12} x2={w - padR} y2={yBase(i) - 12} stroke="#101827" strokeWidth={1} />')
[void]$tsx.Add('        </g>')
[void]$tsx.Add('      ))}')
[void]$tsx.Add('')
[void]$tsx.Add('      <path d={mkPath((s) => s.d0, 0)} fill="none" stroke="#93b8ff" strokeWidth={2.5} opacity={0.95} />')
[void]$tsx.Add('      <path d={mkPath((s) => s.q0, 1)} fill="none" stroke="#00ff95" strokeWidth={2.5} opacity={0.95} />')
[void]$tsx.Add('      <path d={mkPath((s) => s.q1, 2)} fill="none" stroke="#ffd166" strokeWidth={2.5} opacity={0.95} />')
[void]$tsx.Add('      <path d={mkPath((s) => s.clk, 3)} fill="none" stroke="#ff6b6b" strokeWidth={2.5} opacity={0.95} />')
[void]$tsx.Add('    </svg>')
[void]$tsx.Add('  );')
[void]$tsx.Add('}')
[void]$tsx.Add('')
[void]$tsx.Add('function SvgGraph(props: { outs: Outs }) {')
[void]$tsx.Add('  const { outs } = props;')
[void]$tsx.Add('  const g = demoShift2;')
[void]$tsx.Add('  const w = 560;')
[void]$tsx.Add('  const h = 240;')
[void]$tsx.Add('  return (')
[void]$tsx.Add('    <svg width={w} height={h} style={{ border: "1px solid #2a3a52", borderRadius: 14, background: "#070d16" }}>')
[void]$tsx.Add('      {g.edges.map((e) => {')
[void]$tsx.Add('        const a = g.nodes.find((n) => n.id === e.from);')
[void]$tsx.Add('        const b = g.nodes.find((n) => n.id === e.to);')
[void]$tsx.Add('        if (!a || !b) return null;')
[void]$tsx.Add('        const x1 = a.x + 52;')
[void]$tsx.Add('        const y1 = a.y;')
[void]$tsx.Add('        const x2 = b.x - 52;')
[void]$tsx.Add('        const y2 = b.y;')
[void]$tsx.Add('        const mx = (x1 + x2) / 2;')
[void]$tsx.Add('        const d = `M ${x1} ${y1} C ${mx} ${y1}, ${mx} ${y2}, ${x2} ${y2}`;')
[void]$tsx.Add('        return <path key={e.id} d={d} fill="none" stroke="#93b8ff" strokeWidth={2.5} opacity={0.9} />;')
[void]$tsx.Add('      })}')
[void]$tsx.Add('')
[void]$tsx.Add('      {g.nodes.map((n) => {')
[void]$tsx.Add('        const out = (outs[n.id] ?? 0) as Bit;')
[void]$tsx.Add('        const rx = 54;')
[void]$tsx.Add('        const ry = 24;')
[void]$tsx.Add('        return (')
[void]$tsx.Add('          <g key={n.id}>')
[void]$tsx.Add('            <rect x={n.x - rx} y={n.y - ry} width={rx * 2} height={ry * 2} rx={12} ry={12} fill="#0b1422" stroke="#3b557a" />')
[void]$tsx.Add('            <text x={n.x} y={n.y - 4} textAnchor="middle" fontSize="13" fill="#ffffff" fontFamily="ui-sans-serif, system-ui">{n.label}</text>')
[void]$tsx.Add('            <text x={n.x} y={n.y + 16} textAnchor="middle" fontSize="14" fill="#00ff95" fontFamily="ui-monospace, SFMono-Regular, Menlo">{bitLabel(out)}</text>')
[void]$tsx.Add('          </g>')
[void]$tsx.Add('        );')
[void]$tsx.Add('      })}')
[void]$tsx.Add('    </svg>')
[void]$tsx.Add('  );')
[void]$tsx.Add('}')
[void]$tsx.Add('')
[void]$tsx.Add('export function DemoShift2Panel() {')
[void]$tsx.Add('  useEffect(() => { console.log("ACOMPUTE: DemoShift2Panel mounted"); }, []);')
[void]$tsx.Add('')
[void]$tsx.Add('  const [d0, setD0] = useState<Bit>(0);')
[void]$tsx.Add('  const [s, setS] = useState(() => initialState());')
[void]$tsx.Add('  const [mode, setMode] = useState<Mode>("engine");')
[void]$tsx.Add('  const [seqText, setSeqText] = useState<string>("1010010");')
[void]$tsx.Add('  const [seqIdx, setSeqIdx] = useState<number>(0);')
[void]$tsx.Add('  const [auto, setAuto] = useState<boolean>(true);')
[void]$tsx.Add('  const [showcase, setShowcase] = useState<boolean>(true);')
[void]$tsx.Add('  const [periodMs, setPeriodMs] = useState<number>(650);')
[void]$tsx.Add('  const [clkVis, setClkVis] = useState<Bit>(0);')
[void]$tsx.Add('  const [samples, setSamples] = useState<Sample[]>([]);')
[void]$tsx.Add('  const [phase, setPhase] = useState<Phase>("low");')
[void]$tsx.Add('  const [playhead, setPlayhead] = useState<number>(0);')
[void]$tsx.Add('  const [trace, setTrace] = useState<TraceEntry[]>([]);')
[void]$tsx.Add('')
[void]$tsx.Add('  const modeRef = useRef<Mode>(mode);')
[void]$tsx.Add('  const d0Ref = useRef<Bit>(d0);')
[void]$tsx.Add('  const periodRef = useRef<number>(periodMs);')
[void]$tsx.Add('  const autoRef = useRef<boolean>(auto);')
[void]$tsx.Add('  const showcaseRef = useRef<boolean>(showcase);')
[void]$tsx.Add('  const seqTextRef = useRef<string>(seqText);')
[void]$tsx.Add('  const seqIdxRef = useRef<number>(seqIdx);')
[void]$tsx.Add('  const phaseRef = useRef<Phase>(phase);')
[void]$tsx.Add('  const tickRef = useRef<number>(0);')
[void]$tsx.Add('')
[void]$tsx.Add('  useEffect(() => { modeRef.current = mode; }, [mode]);')
[void]$tsx.Add('  useEffect(() => { d0Ref.current = d0; }, [d0]);')
[void]$tsx.Add('  useEffect(() => { periodRef.current = periodMs; }, [periodMs]);')
[void]$tsx.Add('  useEffect(() => { autoRef.current = auto; }, [auto]);')
[void]$tsx.Add('  useEffect(() => { showcaseRef.current = showcase; }, [showcase]);')
[void]$tsx.Add('  useEffect(() => { seqTextRef.current = seqText; }, [seqText]);')
[void]$tsx.Add('  useEffect(() => { seqIdxRef.current = seqIdx; }, [seqIdx]);')
[void]$tsx.Add('  useEffect(() => { phaseRef.current = phase; }, [phase]);')
[void]$tsx.Add('')
[void]$tsx.Add('  const outs = useMemo(() => {')
[void]$tsx.Add('    return evalGraph(s, demoShift2, { D0: d0 });')
[void]$tsx.Add('  }, [s, d0]);')
[void]$tsx.Add('')
[void]$tsx.Add('  const q0 = (outs["Q0"] ?? 0) as Bit;')
[void]$tsx.Add('  const q1 = (outs["Q1"] ?? 0) as Bit;')
[void]$tsx.Add('')
[void]$tsx.Add('  function appendTrace(bit: Bit, st: any, clk: Bit, nextPhase: Phase, nextSeqIdx: number) {')
[void]$tsx.Add('    const o = evalGraph(st, demoShift2, { D0: bit });')
[void]$tsx.Add('    const entry: TraceEntry = {')
[void]$tsx.Add('      tick: tickRef.current + 1,')
[void]$tsx.Add('      phase: nextPhase,')
[void]$tsx.Add('      d0: bit,')
[void]$tsx.Add('      q0: ((o["Q0"] ?? 0) as Bit),')
[void]$tsx.Add('      q1: ((o["Q1"] ?? 0) as Bit),')
[void]$tsx.Add('      clk,')
[void]$tsx.Add('      mode: modeRef.current,')
[void]$tsx.Add('      seqIdx: nextSeqIdx,')
[void]$tsx.Add('    };')
[void]$tsx.Add('    tickRef.current = entry.tick;')
[void]$tsx.Add('    setTrace((prev) => {')
[void]$tsx.Add('      const next = [...prev, entry];')
[void]$tsx.Add('      const keep = 24;')
[void]$tsx.Add('      if (next.length <= keep) return next;')
[void]$tsx.Add('      return next.slice(next.length - keep);')
[void]$tsx.Add('    });')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  function manualShift(prev: any, bit: Bit): any {')
[void]$tsx.Add('    const prevSeq = (prev && prev.seq) ? prev.seq : {};')
[void]$tsx.Add('    const prevQ0 = ((prevSeq["Q0"] ?? 0) as Bit);')
[void]$tsx.Add('    const nextSeq: any = { ...prevSeq, Q0: bit, Q1: prevQ0 };')
[void]$tsx.Add('    return { ...prev, clk: 0, seq: nextSeq };')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  function pushSample(bit: Bit, st: any, clk: Bit) {')
[void]$tsx.Add('    const o = evalGraph(st, demoShift2, { D0: bit });')
[void]$tsx.Add('    const nq0 = ((o["Q0"] ?? 0) as Bit);')
[void]$tsx.Add('    const nq1 = ((o["Q1"] ?? 0) as Bit);')
[void]$tsx.Add('    const smp: Sample = { d0: bit, q0: nq0, q1: nq1, clk };')
[void]$tsx.Add('    setSamples((prev) => {')
[void]$tsx.Add('      const next = [...prev, smp];')
[void]$tsx.Add('      const keep = 60;')
[void]$tsx.Add('      if (next.length <= keep) return next;')
[void]$tsx.Add('      return next.slice(next.length - keep);')
[void]$tsx.Add('    });')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  function pulseAnimated(bit: Bit) {')
[void]$tsx.Add('    const highMs = clamp(Math.floor(periodRef.current * 0.25), 80, 240);')
[void]$tsx.Add('    setClkVis(1);')
[void]$tsx.Add('    setPhase("rise");')
[void]$tsx.Add('')
[void]$tsx.Add('    setS((prev) => {')
[void]$tsx.Add('      const next = (modeRef.current === "manual") ? manualShift(prev, bit) : transition(prev, demoShift2, { D0: bit }, 1);')
[void]$tsx.Add('      pushSample(bit, next, 1);')
[void]$tsx.Add('      appendTrace(bit, next, 1, "rise", seqIdxRef.current);')
[void]$tsx.Add('      return next;')
[void]$tsx.Add('    });')
[void]$tsx.Add('')
[void]$tsx.Add('    window.setTimeout(() => {')
[void]$tsx.Add('      setPhase("fall");')
[void]$tsx.Add('      setS((prev) => {')
[void]$tsx.Add('        const next = (modeRef.current === "manual") ? prev : transition(prev, demoShift2, { D0: bit }, 0);')
[void]$tsx.Add('        pushSample(bit, next, 0);')
[void]$tsx.Add('        appendTrace(bit, next, 0, "fall", seqIdxRef.current);')
[void]$tsx.Add('        return next;')
[void]$tsx.Add('      });')
[void]$tsx.Add('      setClkVis(0);')
[void]$tsx.Add('      setPhase("low");')
[void]$tsx.Add('    }, highMs);')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  function currentSeqBit(): Bit {')
[void]$tsx.Add('    const bits = onlyBits(seqTextRef.current);')
[void]$tsx.Add('    if (bits.length === 0) return d0Ref.current;')
[void]$tsx.Add('    const i = seqIdxRef.current % bits.length;')
[void]$tsx.Add('    return (bits.charAt(i) === "1" ? 1 : 0) as Bit;')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  function stepSequenceOnce() {')
[void]$tsx.Add('    const bits = onlyBits(seqTextRef.current);')
[void]$tsx.Add('    if (bits.length === 0) {')
[void]$tsx.Add('      pulseAnimated(d0Ref.current);')
[void]$tsx.Add('      return;')
[void]$tsx.Add('    }')
[void]$tsx.Add('    const i = seqIdxRef.current % bits.length;')
[void]$tsx.Add('    const b = (bits.charAt(i) === "1" ? 1 : 0) as Bit;')
[void]$tsx.Add('    setD0(b);')
[void]$tsx.Add('    pulseAnimated(b);')
[void]$tsx.Add('    setSeqIdx(i + 1);')
[void]$tsx.Add('    setPlayhead((x) => x + 1);')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  function loadSequenceReset() {')
[void]$tsx.Add('    const bits = onlyBits(seqText);')
[void]$tsx.Add('    setSeqText(bits);')
[void]$tsx.Add('    setSeqIdx(0);')
[void]$tsx.Add('    setS(() => initialState());')
[void]$tsx.Add('    setSamples([]);')
[void]$tsx.Add('    setTrace([]);')
[void]$tsx.Add('    tickRef.current = 0;')
[void]$tsx.Add('    setClkVis(0);')
[void]$tsx.Add('    setPhase("low");')
[void]$tsx.Add('    setPlayhead(0);')
[void]$tsx.Add('    if (bits.length > 0) {')
[void]$tsx.Add('      const b = (bits.charAt(0) === "1" ? 1 : 0) as Bit;')
[void]$tsx.Add('      setD0(b);')
[void]$tsx.Add('    }')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  function showcaseTick() {')
[void]$tsx.Add('    if (!showcaseRef.current) return;')
[void]$tsx.Add('    const p = phaseRef.current;')
[void]$tsx.Add('    if (p === "low" || p === "fall") {')
[void]$tsx.Add('      stepSequenceOnce();')
[void]$tsx.Add('      return;')
[void]$tsx.Add('    }')
[void]$tsx.Add('  }')
[void]$tsx.Add('')
[void]$tsx.Add('  useEffect(() => {')
[void]$tsx.Add('    const base = clamp(periodRef.current, 180, 3000);')
[void]$tsx.Add('    const tickMs = clamp(Math.floor(base), 120, 3000);')
[void]$tsx.Add('    const id = window.setInterval(() => {')
[void]$tsx.Add('      if (showcaseRef.current) {')
[void]$tsx.Add('        showcaseTick();')
[void]$tsx.Add('      } else if (autoRef.current) {')
[void]$tsx.Add('        stepSequenceOnce();')
[void]$tsx.Add('      }')
[void]$tsx.Add('    }, tickMs);')
[void]$tsx.Add('    return () => window.clearInterval(id);')
[void]$tsx.Add('  }, [auto, periodMs, showcase]);')
[void]$tsx.Add('')
[void]$tsx.Add('  const clkDot = clkVis === 1 ? "#00ff95" : "#3b557a";')
[void]$tsx.Add('  const bitNow = currentSeqBit();')
[void]$tsx.Add('  const latestTrace = trace.length > 0 ? trace[trace.length - 1] : null;')
[void]$tsx.Add('')
[void]$tsx.Add('  return (')
[void]$tsx.Add('    <div style={{ padding: 16, color: "#ffffff", fontFamily: "ui-sans-serif, system-ui", background: "#05070c", minHeight: "100vh" }}>')
[void]$tsx.Add('      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 10, flexWrap: "wrap" }}>')
[void]$tsx.Add('        <h1 style={{ margin: 0, fontSize: 22 }}>ACompute - MVP3 Shift Register (2x DFF)</h1>')
[void]$tsx.Add('        <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.9 }}>SHOWCASE v3 + TRACE INTROSPECTION</div>')
[void]$tsx.Add('      </div>')
[void]$tsx.Add('')
[void]$tsx.Add('      <div style={{ marginTop: 8, opacity: 0.92 }}>')
[void]$tsx.Add('        D0 -&gt; Q0, and Q0 -&gt; D1 -&gt; Q1. Pulse performs clk 0 -&gt; 1 -&gt; 0 (rising edge capture).')
[void]$tsx.Add('      </div>')
[void]$tsx.Add('')
[void]$tsx.Add('      <div style={{ display: "flex", gap: 10, marginTop: 14, alignItems: "center", flexWrap: "wrap" }}>')
[void]$tsx.Add('        <button onClick={() => setD0(d0 === 1 ? 0 : 1)} style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}>')
[void]$tsx.Add('          Toggle D0 (now {bitLabel(d0)})')
[void]$tsx.Add('        </button>')
[void]$tsx.Add('        <button onClick={() => pulseAnimated(d0)} style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#152540", color: "#ffffff" }}>')
[void]$tsx.Add('          Pulse (0 -&gt; 1 -&gt; 0)')
[void]$tsx.Add('        </button>')
[void]$tsx.Add('        <div style={{ display: "flex", gap: 10, alignItems: "center" }}>')
[void]$tsx.Add('          <div style={{ width: 10, height: 10, borderRadius: 999, background: clkDot, boxShadow: clkVis ? "0 0 12px rgba(0,255,149,0.55)" : "none" }} />')
[void]$tsx.Add('          <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.95 }}>')
[void]$tsx.Add('            Q0={bitLabel(q0)} Q1={bitLabel(q1)} clk={bitLabel(clkVis)} phase={phase}')
[void]$tsx.Add('          </div>')
[void]$tsx.Add('        </div>')
[void]$tsx.Add('      </div>')
[void]$tsx.Add('')
[void]$tsx.Add('      <div style={{ display: "flex", gap: 10, marginTop: 12, alignItems: "center", flexWrap: "wrap" }}>')
[void]$tsx.Add('        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>')
[void]$tsx.Add('          <span style={{ opacity: 0.95 }}>Mode</span>')
[void]$tsx.Add('          <select value={mode} onChange={(e) => setMode(e.target.value as Mode)} style={{ padding: "6px 8px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}>')
[void]$tsx.Add('            <option value="engine">Engine (transition)</option>')
[void]$tsx.Add('            <option value="manual">Manual (guaranteed shift)</option>')
[void]$tsx.Add('          </select>')
[void]$tsx.Add('        </label>')
[void]$tsx.Add('        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>')
[void]$tsx.Add('          <span style={{ opacity: 0.95 }}>Input bits</span>')
[void]$tsx.Add('          <input value={seqText} onChange={(e) => setSeqText(onlyBits(e.target.value))} placeholder="e.g. 101001" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff", width: 220 }} />')
[void]$tsx.Add('        </label>')
[void]$tsx.Add('        <button onClick={loadSequenceReset} style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}>')
[void]$tsx.Add('          Load (reset)')
[void]$tsx.Add('        </button>')
[void]$tsx.Add('        <button onClick={stepSequenceOnce} style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#152540", color: "#ffffff" }}>')
[void]$tsx.Add('          Step next bit')
[void]$tsx.Add('        </button>')
[void]$tsx.Add('        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>')
[void]$tsx.Add('          <span style={{ opacity: 0.95 }}>Auto</span>')
[void]$tsx.Add('          <input type="checkbox" checked={auto} onChange={(e) => setAuto(e.target.checked)} />')
[void]$tsx.Add('        </label>')
[void]$tsx.Add('        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>')
[void]$tsx.Add('          <span style={{ opacity: 0.95 }}>Showcase</span>')
[void]$tsx.Add('          <input type="checkbox" checked={showcase} onChange={(e) => setShowcase(e.target.checked)} />')
[void]$tsx.Add('        </label>')
[void]$tsx.Add('        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>')
[void]$tsx.Add('          <span style={{ opacity: 0.95 }}>Period</span>')
[void]$tsx.Add('          <input type="range" min={180} max={1400} step={10} value={periodMs} onChange={(e) => setPeriodMs(parseInt(e.target.value || "650", 10))} />')
[void]$tsx.Add('          <span style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.9 }}>{periodMs}ms</span>')
[void]$tsx.Add('        </label>')
[void]$tsx.Add('        <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.9 }}>')
[void]$tsx.Add('          seqIdx={seqIdx} nextBit={bitLabel(bitNow)} samples={samples.length} ticks={tickRef.current}')
[void]$tsx.Add('        </div>')
[void]$tsx.Add('      </div>')
[void]$tsx.Add('')
[void]$tsx.Add('      <div style={{ marginTop: 12 }}>')
[void]$tsx.Add('        <Waveform samples={samples} playhead={playhead} phase={phase} />')
[void]$tsx.Add('      </div>')
[void]$tsx.Add('')
[void]$tsx.Add('      <div style={{ marginTop: 14, display: "flex", gap: 12, flexWrap: "wrap", alignItems: "flex-start" }}>')
[void]$tsx.Add('        <div><SvgGraph outs={outs} /></div>')
[void]$tsx.Add('        <div style={{ flex: 1, minWidth: 360, display: "grid", gap: 12 }}>')
[void]$tsx.Add('          <div style={{ border: "1px solid #2a3a52", borderRadius: 12, padding: 12, background: "#070d16" }}>')
[void]$tsx.Add('            <div style={{ fontWeight: 700, marginBottom: 6 }}>Latest introspection snapshot</div>')
[void]$tsx.Add('            <pre style={{ margin: 0, fontSize: 12, whiteSpace: "pre-wrap", color: "#ffffff" }}>{JSON.stringify({')
[void]$tsx.Add('              tick: tickRef.current,')
[void]$tsx.Add('              phase,')
[void]$tsx.Add('              mode,')
[void]$tsx.Add('              d0,')
[void]$tsx.Add('              clk: clkVis,')
[void]$tsx.Add('              seq: (s as any).seq,')
[void]$tsx.Add('              outs,')
[void]$tsx.Add('            }, null, 2)}</pre>')
[void]$tsx.Add('          </div>')
[void]$tsx.Add('')
[void]$tsx.Add('          <div style={{ border: "1px solid #2a3a52", borderRadius: 12, padding: 12, background: "#070d16" }}>')
[void]$tsx.Add('            <div style={{ fontWeight: 700, marginBottom: 6 }}>Execution trace ledger</div>')
[void]$tsx.Add('            <div style={{ maxHeight: 260, overflow: "auto", border: "1px solid #162235", borderRadius: 10 }}>')
[void]$tsx.Add('              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>')
[void]$tsx.Add('                <thead>')
[void]$tsx.Add('                  <tr>')
[void]$tsx.Add('                    <th style={{ textAlign: "left", padding: 8, borderBottom: "1px solid #22314a" }}>tick</th>')
[void]$tsx.Add('                    <th style={{ textAlign: "left", padding: 8, borderBottom: "1px solid #22314a" }}>phase</th>')
[void]$tsx.Add('                    <th style={{ textAlign: "left", padding: 8, borderBottom: "1px solid #22314a" }}>D0</th>')
[void]$tsx.Add('                    <th style={{ textAlign: "left", padding: 8, borderBottom: "1px solid #22314a" }}>Q0</th>')
[void]$tsx.Add('                    <th style={{ textAlign: "left", padding: 8, borderBottom: "1px solid #22314a" }}>Q1</th>')
[void]$tsx.Add('                    <th style={{ textAlign: "left", padding: 8, borderBottom: "1px solid #22314a" }}>clk</th>')
[void]$tsx.Add('                    <th style={{ textAlign: "left", padding: 8, borderBottom: "1px solid #22314a" }}>mode</th>')
[void]$tsx.Add('                    <th style={{ textAlign: "left", padding: 8, borderBottom: "1px solid #22314a" }}>seqIdx</th>')
[void]$tsx.Add('                  </tr>')
[void]$tsx.Add('                </thead>')
[void]$tsx.Add('                <tbody>')
[void]$tsx.Add('                  {trace.slice().reverse().map((t) => (')
[void]$tsx.Add('                    <tr key={`tick-${t.tick}-${t.phase}`}>')
[void]$tsx.Add('                      <td style={{ padding: 8, borderBottom: "1px solid #162235", fontFamily: "ui-monospace, SFMono-Regular, Menlo" }}>{t.tick}</td>')
[void]$tsx.Add('                      <td style={{ padding: 8, borderBottom: "1px solid #162235", fontFamily: "ui-monospace, SFMono-Regular, Menlo" }}>{t.phase}</td>')
[void]$tsx.Add('                      <td style={{ padding: 8, borderBottom: "1px solid #162235", fontFamily: "ui-monospace, SFMono-Regular, Menlo" }}>{bitLabel(t.d0)}</td>')
[void]$tsx.Add('                      <td style={{ padding: 8, borderBottom: "1px solid #162235", fontFamily: "ui-monospace, SFMono-Regular, Menlo" }}>{bitLabel(t.q0)}</td>')
[void]$tsx.Add('                      <td style={{ padding: 8, borderBottom: "1px solid #162235", fontFamily: "ui-monospace, SFMono-Regular, Menlo" }}>{bitLabel(t.q1)}</td>')
[void]$tsx.Add('                      <td style={{ padding: 8, borderBottom: "1px solid #162235", fontFamily: "ui-monospace, SFMono-Regular, Menlo" }}>{bitLabel(t.clk)}</td>')
[void]$tsx.Add('                      <td style={{ padding: 8, borderBottom: "1px solid #162235", fontFamily: "ui-monospace, SFMono-Regular, Menlo" }}>{t.mode}</td>')
[void]$tsx.Add('                      <td style={{ padding: 8, borderBottom: "1px solid #162235", fontFamily: "ui-monospace, SFMono-Regular, Menlo" }}>{t.seqIdx}</td>')
[void]$tsx.Add('                    </tr>')
[void]$tsx.Add('                  ))}')
[void]$tsx.Add('                  {trace.length === 0 ? (')
[void]$tsx.Add('                    <tr>')
[void]$tsx.Add('                      <td colSpan={8} style={{ padding: 12, opacity: 0.8 }}>No ticks yet. Press Pulse or enable Showcase/Auto.</td>')
[void]$tsx.Add('                    </tr>')
[void]$tsx.Add('                  ) : null}')
[void]$tsx.Add('                </tbody>')
[void]$tsx.Add('              </table>')
[void]$tsx.Add('            </div>')
[void]$tsx.Add('          </div>')
[void]$tsx.Add('')
[void]$tsx.Add('          <div style={{ border: "1px solid #2a3a52", borderRadius: 12, padding: 12, background: "#070d16" }}>')
[void]$tsx.Add('            <div style={{ fontWeight: 700, marginBottom: 6 }}>Latest trace entry</div>')
[void]$tsx.Add('            <pre style={{ margin: 0, fontSize: 12, whiteSpace: "pre-wrap", color: "#ffffff" }}>{JSON.stringify(latestTrace, null, 2)}</pre>')
[void]$tsx.Add('          </div>')
[void]$tsx.Add('        </div>')
[void]$tsx.Add('      </div>')
[void]$tsx.Add('    </div>')
[void]$tsx.Add('  );')
[void]$tsx.Add('}')
WriteUtf8NoBomLf $panelPath (@($tsx.ToArray()))
Write-Host ("PATCH_OK: wrote trace introspection panel " + $panelPath) -ForegroundColor Green
