param([Parameter(Mandatory=$true)][string]$RepoRoot)
$ErrorActionPreference="Stop"
Set-StrictMode -Version Latest

function EnsureDir([string]$p){
  if([string]::IsNullOrWhiteSpace($p)){ throw "EnsureDir: empty path" }
  if(-not (Test-Path -LiteralPath $p -PathType Container)){
    New-Item -ItemType Directory -Force -Path $p | Out-Null
  }
}

function WriteUtf8NoBomLf([string]$Path,[string]$Text){
  if([string]::IsNullOrWhiteSpace($Path)){ throw "WriteUtf8NoBomLf: empty path" }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $t = $Text -replace "`r`n","`n"
  $t = $t -replace "`r","`n"
  if(-not $t.EndsWith("`n")){ $t += "`n" }
  EnsureDir (Split-Path -Parent $Path)
  [System.IO.File]::WriteAllText($Path,$t,$enc)
}

function WriteLines([string]$Path,[string[]]$Lines){
  $txt = ((@($Lines) -join "`n") + "`n")
  WriteUtf8NoBomLf $Path $txt
}

$panelPath = Join-Path $RepoRoot "app\src\acompute\ui\DemoShift2Panel.tsx"
EnsureDir (Split-Path -Parent $panelPath)

WriteLines $panelPath @(
'import React, { useEffect, useMemo, useRef, useState } from "react";'
'import type { Bit } from "../core/types";'
'import { initialState } from "../core/state";'
'import { transition } from "../core/transition";'
'import { evalGraph } from "../engine/eval";'
'import { demoShift2 } from "../demos/demo_shift2";'
''
'type Outs = Record<string, Bit>;'
'type Mode = "engine" | "manual";'
''
'function bitLabel(b: Bit): string {'
'  return b === 1 ? "1" : "0";'
'}'
''
'function onlyBits(s: string): string {'
'  return (s || "").replace(/[^01]/g, "");'
'}'
''
'function clamp(n: number, lo: number, hi: number): number {'
'  if (n < lo) return lo;'
'  if (n > hi) return hi;'
'  return n;'
'}'
''
'type Sample = { d0: Bit; q0: Bit; q1: Bit; clk: Bit };'
''
'function Waveform(props: { samples: Sample[] }) {'
'  const { samples } = props;'
'  const w = 860;'
'  const rowH = 34;'
'  const padL = 70;'
'  const padR = 16;'
'  const padT = 10;'
'  const n = Math.max(2, samples.length);'
'  const step = (w - padL - padR) / (n - 1);'
''
'  function yBase(row: number): number {'
'    return padT + row * rowH + 18;'
'  }'
''
'  function mkPath(get: (s: Sample) => Bit, row: number): string {'
'    if (samples.length === 0) return "";'
'    const y0 = yBase(row);'
'    const hi = y0 - 12;'
'    const lo = y0 + 8;'
'    let d = "";'
'    let prev = get(samples[0]);'
'    let x = padL;'
'    let y = prev ? hi : lo;'
'    d += `M ${x} ${y}`;'
'    for (let i = 1; i < samples.length; i++) {'
'      const v = get(samples[i]);'
'      const nx = padL + i * step;'
'      const ny = v ? hi : lo;'
'      d += ` L ${nx} ${y}`;'
'      if (ny !== y) {'
'        d += ` L ${nx} ${ny}`;'
'      }'
'      x = nx;'
'      y = ny;'
'      prev = v;'
'    }'
'    return d;'
'  }'
''
'  const h = padT + rowH * 4 + 10;'
''
'  return ('
'    <svg width={w} height={h} style={{ border: "1px solid #2a3a52", borderRadius: 12, background: "#070d16" }}>'
'      <text x={12} y={18} fontSize={12} fill="#ffffff" fontFamily="ui-monospace, SFMono-Regular, Menlo" opacity={0.9}>Waveform (last {samples.length} samples)</text>'
''
'      {["D0","Q0","Q1","clk"].map((lab, i) => ('
'        <g key={lab}>'
'          <text x={12} y={yBase(i)} fontSize={12} fill="#ffffff" fontFamily="ui-monospace, SFMono-Regular, Menlo" opacity={0.9}>{lab}</text>'
'          <line x1={padL} y1={yBase(i)+8} x2={w-padR} y2={yBase(i)+8} stroke="#1c2a3b" strokeWidth={1} />'
'          <line x1={padL} y1={yBase(i)-12} x2={w-padR} y2={yBase(i)-12} stroke="#101827" strokeWidth={1} />'
'        </g>'
'      ))}'
''
'      <path d={mkPath((s) => s.d0, 0)} fill="none" stroke="#93b8ff" strokeWidth={2.5} opacity={0.95} />'
'      <path d={mkPath((s) => s.q0, 1)} fill="none" stroke="#00ff95" strokeWidth={2.5} opacity={0.95} />'
'      <path d={mkPath((s) => s.q1, 2)} fill="none" stroke="#ffd166" strokeWidth={2.5} opacity={0.95} />'
'      <path d={mkPath((s) => s.clk, 3)} fill="none" stroke="#ff6b6b" strokeWidth={2.5} opacity={0.95} />'
'    </svg>'
'  );'
'}'
''
'function SvgGraph(props: { outs: Outs }) {'
'  const { outs } = props;'
'  const g = demoShift2;'
'  const w = 560;'
'  const h = 240;'
'  return ('
'    <svg width={w} height={h} style={{ border: "1px solid #2a3a52", borderRadius: 14, background: "#070d16" }}>'
'      {g.edges.map((e) => {'
'        const a = g.nodes.find((n) => n.id === e.from);'
'        const b = g.nodes.find((n) => n.id === e.to);'
'        if (!a || !b) return null;'
'        const x1 = a.x + 52;'
'        const y1 = a.y;'
'        const x2 = b.x - 52;'
'        const y2 = b.y;'
'        const mx = (x1 + x2) / 2;'
'        const d = `M ${x1} ${y1} C ${mx} ${y1}, ${mx} ${y2}, ${x2} ${y2}`;'
'        return <path key={e.id} d={d} fill="none" stroke="#93b8ff" strokeWidth={2.5} opacity={0.9} />;'
'      })}'
''
'      {g.nodes.map((n) => {'
'        const out = (outs[n.id] ?? 0) as Bit;'
'        const rx = 54;'
'        const ry = 24;'
'        return ('
'          <g key={n.id}>'
'            <rect x={n.x - rx} y={n.y - ry} width={rx * 2} height={ry * 2} rx={12} ry={12} fill="#0b1422" stroke="#3b557a" />'
'            <text x={n.x} y={n.y - 4} textAnchor="middle" fontSize="13" fill="#ffffff" fontFamily="ui-sans-serif, system-ui">{n.label}</text>'
'            <text x={n.x} y={n.y + 16} textAnchor="middle" fontSize="14" fill="#00ff95" fontFamily="ui-monospace, SFMono-Regular, Menlo">{bitLabel(out as Bit)}</text>'
'          </g>'
'        );'
'      })}'
'    </svg>'
'  );'
'}'
''
'export function DemoShift2Panel() {'
'  const [d0, setD0] = useState<Bit>(0);'
'  const [s, setS] = useState(() => initialState());'
'  const [mode, setMode] = useState<Mode>("engine");'
''
'  const [seqText, setSeqText] = useState<string>("1010010");'
'  const [seqIdx, setSeqIdx] = useState<number>(0);'
''
'  const [auto, setAuto] = useState<boolean>(true);'
'  const [periodMs, setPeriodMs] = useState<number>(650);'
'  const [clkVis, setClkVis] = useState<Bit>(0);'
'  const [samples, setSamples] = useState<Sample[]>([]);'
''
'  const modeRef = useRef<Mode>(mode);'
'  const d0Ref = useRef<Bit>(d0);'
'  const periodRef = useRef<number>(periodMs);'
'  const autoRef = useRef<boolean>(auto);'
'  const seqTextRef = useRef<string>(seqText);'
'  const seqIdxRef = useRef<number>(seqIdx);'
''
'  useEffect(() => { modeRef.current = mode; }, [mode]);'
'  useEffect(() => { d0Ref.current = d0; }, [d0]);'
'  useEffect(() => { periodRef.current = periodMs; }, [periodMs]);'
'  useEffect(() => { autoRef.current = auto; }, [auto]);'
'  useEffect(() => { seqTextRef.current = seqText; }, [seqText]);'
'  useEffect(() => { seqIdxRef.current = seqIdx; }, [seqIdx]);'
''
'  const outs = useMemo(() => {'
'    return evalGraph(s, demoShift2, { D0: d0 });'
'  }, [s, d0]);'
''
'  const q0 = (outs["Q0"] ?? 0) as Bit;'
'  const q1 = (outs["Q1"] ?? 0) as Bit;'
''
'  function manualShift(prev: any, bit: Bit): any {'
'    const prevSeq = (prev && prev.seq) ? prev.seq : {};'
'    const prevQ0 = ((prevSeq["Q0"] ?? 0) as Bit);'
'    const nextSeq: any = { ...prevSeq, Q0: bit, Q1: prevQ0 };'
'    return { ...prev, clk: 0, seq: nextSeq };'
'  }'
''
'  function pushSample(bit: Bit, st: any, clk: Bit) {'
'    const o = evalGraph(st, demoShift2, { D0: bit });'
'    const nq0 = ((o["Q0"] ?? 0) as Bit);'
'    const nq1 = ((o["Q1"] ?? 0) as Bit);'
'    const smp: Sample = { d0: bit, q0: nq0, q1: nq1, clk };'
'    setSamples((prev) => {'
'      const next = [...prev, smp];'
'      const keep = 60;'
'      if (next.length <= keep) return next;'
'      return next.slice(next.length - keep);'
'    });'
'  }'
''
'  function pulseAnimated(bit: Bit) {'
'    const highMs = clamp(Math.floor(periodRef.current * 0.25), 80, 240);'
''
'    setClkVis(1);'
''
'    setS((prev) => {'
'      if (modeRef.current === "manual") {'
'        const next = manualShift(prev, bit);'
'        pushSample(bit, next, 1);'
'        return next;'
'      }'
'      const s1 = transition(prev, demoShift2, { D0: bit }, 1);'
'      pushSample(bit, s1, 1);'
'      return s1;'
'    });'
''
'    window.setTimeout(() => {'
'      setS((prev) => {'
'        if (modeRef.current === "manual") {'
'          pushSample(bit, prev, 0);'
'          return prev;'
'        }'
'        const s2 = transition(prev, demoShift2, { D0: bit }, 0);'
'        pushSample(bit, s2, 0);'
'        return s2;'
'      });'
'      setClkVis(0);'
'    }, highMs);'
'  }'
''
'  function currentSeqBit(): Bit {'
'    const bits = onlyBits(seqTextRef.current);'
'    if (bits.length === 0) return d0Ref.current;'
'    const i = seqIdxRef.current % bits.length;'
'    return (bits.charAt(i) === "1" ? 1 : 0) as Bit;'
'  }'
''
'  function stepSequenceOnce() {'
'    const bits = onlyBits(seqTextRef.current);'
'    if (bits.length === 0) {'
'      pulseAnimated(d0Ref.current);'
'      return;'
'    }'
'    const i = seqIdxRef.current % bits.length;'
'    const b = (bits.charAt(i) === "1" ? 1 : 0) as Bit;'
'    setD0(b);'
'    pulseAnimated(b);'
'    setSeqIdx(i + 1);'
'  }'
''
'  function loadSequenceReset() {'
'    const bits = onlyBits(seqText);'
'    setSeqText(bits);'
'    setSeqIdx(0);'
'    setS(() => initialState());'
'    setSamples([]);'
'    setClkVis(0);'
'    if (bits.length > 0) {'
'      const b = (bits.charAt(0) === "1" ? 1 : 0) as Bit;'
'      setD0(b);'
'    }'
'  }'
''
'  useEffect(() => {'
'    if (!autoRef.current) return;'
'    const id = window.setInterval(() => {'
'      if (!autoRef.current) return;'
'      stepSequenceOnce();'
'    }, clamp(periodRef.current, 120, 3000));'
'    return () => window.clearInterval(id);'
'  }, [auto, periodMs]);'
''
'  const clkDot = clkVis === 1 ? "#00ff95" : "#3b557a";'
'  const bitNow = currentSeqBit();'
''
'  return ('
'    <div style={{ padding: 16, color: "#ffffff", fontFamily: "ui-sans-serif, system-ui", background: "#05070c", minHeight: "100vh" }}>'
'      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 10, flexWrap: "wrap" }}>'
'        <h1 style={{ margin: 0, fontSize: 22 }}>ACompute - MVP3 Shift Register (2x DFF)</h1>'
'        <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.9 }}>SHOWCASE v2 + WAVEFORM</div>'
'      </div>'
''
'      <div style={{ marginTop: 8, opacity: 0.92 }}>'
'        D0 -&gt; Q0, and Q0 -&gt; D1 -&gt; Q1. Pulse performs clk 0-&gt;1-&gt;0 (rising edge capture).'
'      </div>'
''
'      <div style={{ display: "flex", gap: 10, marginTop: 14, alignItems: "center", flexWrap: "wrap" }}>'
'        <button'
'          onClick={() => setD0(d0 === 1 ? 0 : 1)}'
'          style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}'
'        >'
'          Toggle D0 (now {bitLabel(d0)})'
'        </button>'
''
'        <button'
'          onClick={() => pulseAnimated(d0)}'
'          style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#152540", color: "#ffffff" }}'
'        >'
'          Pulse (0-&gt;1-&gt;0)'
'        </button>'
''
'        <div style={{ display: "flex", gap: 10, alignItems: "center" }}>'
'          <div style={{ width: 10, height: 10, borderRadius: 999, background: clkDot, boxShadow: clkVis ? "0 0 12px rgba(0,255,149,0.55)" : "none" }} />'
'          <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.95 }}>'
'            Q0={bitLabel(q0)} Q1={bitLabel(q1)} clk={bitLabel(clkVis)}'
'          </div>'
'        </div>'
'      </div>'
''
'      <div style={{ display: "flex", gap: 10, marginTop: 12, alignItems: "center", flexWrap: "wrap" }}>'
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>'
'          <span style={{ opacity: 0.95 }}>Mode</span>'
'          <select'
'            value={mode}'
'            onChange={(e) => setMode(e.target.value as Mode)}'
'            style={{ padding: "6px 8px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}'
'          >'
'            <option value="engine">Engine (transition)</option>'
'            <option value="manual">Manual (guaranteed shift)</option>'
'          </select>'
'        </label>'
''
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>'
'          <span style={{ opacity: 0.95 }}>Input bits</span>'
'          <input'
'            value={seqText}'
'            onChange={(e) => setSeqText(onlyBits(e.target.value))}'
'            placeholder="e.g. 101001"'
'            style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff", width: 220 }}'
'          />'
'        </label>'
''
'        <button'
'          onClick={loadSequenceReset}'
'          style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#0b1422", color: "#ffffff" }}'
'        >'
'          Load (reset)'
'        </button>'
''
'        <button'
'          onClick={stepSequenceOnce}'
'          style={{ padding: "8px 12px", borderRadius: 10, border: "1px solid #3b557a", background: "#152540", color: "#ffffff" }}'
'        >'
'          Step next bit'
'        </button>'
''
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>'
'          <span style={{ opacity: 0.95 }}>Auto</span>'
'          <input type="checkbox" checked={auto} onChange={(e) => setAuto(e.target.checked)} />'
'        </label>'
''
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>'
'          <span style={{ opacity: 0.95 }}>Period</span>'
'          <input'
'            type="range"'
'            min={180}'
'            max={1400}'
'            step={10}'
'            value={periodMs}'
'            onChange={(e) => setPeriodMs(parseInt(e.target.value || "650", 10))}'
'          />'
'          <span style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.9 }}>{periodMs}ms</span>'
'        </label>'
''
'        <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo", opacity: 0.9 }}>'
'          seqIdx={seqIdx} nextBit={bitLabel(bitNow)} samples={samples.length}'
'        </div>'
'      </div>'
''
'      <div style={{ marginTop: 12 }}>'
'        <Waveform samples={samples} />'
'      </div>'
''
'      <div style={{ marginTop: 14, display: "flex", gap: 12, flexWrap: "wrap" }}>'
'        <div><SvgGraph outs={outs} /></div>'
'        <div style={{ flex: 1, minWidth: 320, display: "grid", gap: 12 }}>'
'          <div style={{ border: "1px solid #2a3a52", borderRadius: 12, padding: 12, background: "#070d16" }}>'
'            <div style={{ fontWeight: 700, marginBottom: 6 }}>Sequential state (s.seq)</div>'
'            <pre style={{ margin: 0, fontSize: 12, whiteSpace: "pre-wrap", color: "#ffffff" }}>{JSON.stringify((s as any).seq, null, 2)}</pre>'
'          </div>'
'          <div style={{ border: "1px solid #2a3a52", borderRadius: 12, padding: 12, background: "#070d16" }}>'
'            <div style={{ fontWeight: 700, marginBottom: 6 }}>Combinational outs</div>'
'            <pre style={{ margin: 0, fontSize: 12, whiteSpace: "pre-wrap", color: "#ffffff" }}>{JSON.stringify(outs, null, 2)}</pre>'
'          </div>'
'        </div>'
'      </div>'
'    </div>'
'  );'
'}'
)

Write-Host ("PATCH_OK: wrote " + $panelPath) -ForegroundColor Green
Write-Host "NOTE: in the Vite terminal press r + Enter to reload" -ForegroundColor Yellow
